# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20160724_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('GEN', 'General information'), ('FOO', 'Food and drinks'), ('SLE', 'Sleeping'), ('CUL', 'Culture'), ('OUT', 'Outside'), ('TRA', 'Transport'), ('STA', 'Staying safe')], default='GEN', max_length=3),
        ),
    ]
