# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 10:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20160816_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author_profile',
        ),
    ]
