# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_article_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='date published'),
        ),
    ]
